version: '4.0'

networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:1.8.10
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    volumes:
    - influxdb_lib:/var/lib/influxdb

  grafana:
    image: grafana/grafana:10.2.2
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - grafana_lib:/var/lib/grafana
      - ./dashboards:/var/lib/grafana_dashboards
      #- grafana_etc:/etc/grafana
      - grafana_logs:/var/log/grafana
      - ./grafana_config/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana_config/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml

  k6:
    image: grafana/k6:0.48.0
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts


volumes:
  influxdb_lib:
  grafana_etc:
  grafana_lib:
  grafana_logs: